# reference https://longhorn.io/docs/1.4.0/deploy/install/#installation-requirements
- name: install longhorn dependencies
  apt:
    update_cache: yes
    name:
      - open-iscsi
      - bash
      - curl
      - grep
    state: present
